import * as React from "react";
import { A2UI_CATALOG } from "./catalog";
import { resolveBinding } from "./binding";
import type { A2UIAction, A2UIComponent, A2UITree } from "./types";

interface Props {
  tree: A2UITree;
  onAction?: (action: A2UIAction) => void;
}

/**
 * A2UI renderer.
 * - Renders flat component list addressed by ID, walking from `tree.root`.
 * - Maintains per-tree state, seeded from `tree.state`. Server can ship updated
 *   `state` mid-stream; we shallow-merge new top-level keys but preserve user edits.
 * - Missing children show a skeleton placeholder so partial trees stream in cleanly.
 * - User interactions are emitted via `onAction` so the host can forward them
 *   to the agent over AG-UI.
 */
export function A2UIRenderer({ tree, onAction }: Props) {
  const componentMap = React.useMemo(() => {
    const m = new Map<string, A2UIComponent>();
    if (tree && Array.isArray(tree.components)) {
      for (const c of tree.components) m.set(c.id, c);
    }
    return m;
  }, [tree?.components]);

  const [localState, setLocalState] = React.useState<Record<string, unknown>>(tree?.state ?? {});

  // Merge new server-side keys without clobbering user edits already present.
  const seenServerStateRef = React.useRef<string>("");
  React.useEffect(() => {
    const sig = JSON.stringify(tree?.state ?? {});
    if (sig === seenServerStateRef.current) return;
    seenServerStateRef.current = sig;
    setLocalState((prev) => ({ ...(tree.state ?? {}), ...prev }));
  }, [tree.state]);

  const emit = React.useCallback(
    (action: Omit<A2UIAction, "state">) => {
      onAction?.({ ...action, surfaceId: tree.surfaceId, state: localState });
    },
    [onAction, tree.surfaceId, localState],
  );

  const renderChild = React.useCallback(
    (id: string): React.ReactNode => {
      const c = componentMap.get(id);
      if (!c || !c.component) return <Skeleton key={id} />;
      
      let type = "Unknown";
      let data: any = {};

      if (typeof c.component === "string") {
        type = c.component;
        data = c; // Fallback for the flat v0.9-like format often generated by LLM shortcuts
      } else if (typeof c.component === "object") {
        type = Object.keys(c.component)[0];
        data = (c.component as any)[type];
      }

      const Renderer = A2UI_CATALOG[type];
      
      const resolvedProps: Record<string, unknown> = { ...(data ?? {}) };
      // Note: bindings are not standardized in v0.8 the same way, we can skip for now or adapt if needed
      
      if (!Renderer) {
        return (
          <div key={id} className="rounded-md border border-dashed border-border p-2 text-xs text-muted-foreground">
            Unknown A2UI component: <span className="mono">{type}</span>
          </div>
        );
      }
      return (
        <div key={id} className="animate-fade-in" style={{ flexGrow: c.weight ? c.weight : 0 }}>
          {Renderer({
            state: localState,
            setState: setLocalState,
            emit,
            renderChild,
            hasComponent: (cid) => componentMap.has(cid),
            component: c,
            props: resolvedProps,
          })}
        </div>
      );
    },
    [componentMap, localState, emit],
  );

  return <div className="space-y-3">{tree?.root ? renderChild(tree.root) : null}</div>;
}

function Skeleton() {
  return <div className="h-6 rounded-md bg-muted/60 animate-pulse-soft" />;
}
